### ISSUE TITLE
Plugin load failed

### ISSUE THREAD

**Issue by 4rozeN** [HPCesia/hexo-highlighter-shiki#1]
### 我的环境
``` bash
hexo: 7.3.0
hexo-cli: 4.3.2
os: win32 10.0.22631 undefined
node: 20.13.1
"hexo-renderer-markdown-it-plus": "^1.0.6"
"hexo-theme-fluid": "^1.9.8"
```
### 我的配置文件
由于使用fluid主题，所以配置文件目录下存在`_config.yml`和`_config.fluid.yml`两个文件。
我尝试在`_config.yml`文件中配置如下：
``` yaml
syntax_highlighter: shiki
shiki:
  theme: dark-plus
```
并且在`_config.fluid.yml`文件中配置如下：
``` yaml
# 实现高亮的库，对应下面的设置
# Highlight library
# Options: highlightjs | prismjs | shiki
lib: "shiki"
shiki:
  theme: dark-plus # 代码高亮主题
```
### 我的问题
按照README.md文档安装插件之后，尝试执行hexo clean命令时，终端报错：
``` bash
$ hexo clean  
INFO  Validating config
ERROR Plugin load failed: hexo-highlighter-shiki
Error: EISDIR: illegal operation on a directory, read
    at async readFileHandle (node:internal/fs/promises:552:24)
```
### 期望
我想知道这是否是我的环境问题，还是插件问题？
如果是前者，我应当如何调整或者如何补充配置项；如果是后者，希望能有个解决办法，麻烦了。
